// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/history": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/create": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/legal": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/forgot-password" | "/reset-password" | "/register" | "/settings" | "/history" | "/pricing" | "/create" | "/admin" | "/legal" | "/login";
  };
  "routes/forgot-password.jsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/reset-password.jsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/register.jsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/settings.jsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/history.jsx": {
    id: "routes/history";
    page: "/history";
  };
  "routes/pricing.jsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/create.jsx": {
    id: "routes/create";
    page: "/create";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/admin.jsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/legal.jsx": {
    id: "routes/legal";
    page: "/legal";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.jsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.jsx");
  "routes/register": typeof import("./app/routes/register.jsx");
  "routes/settings": typeof import("./app/routes/settings.jsx");
  "routes/history": typeof import("./app/routes/history.jsx");
  "routes/pricing": typeof import("./app/routes/pricing.jsx");
  "routes/create": typeof import("./app/routes/create.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/admin": typeof import("./app/routes/admin.jsx");
  "routes/legal": typeof import("./app/routes/legal.jsx");
  "routes/login": typeof import("./app/routes/login.jsx");
};