import { createClient } from '@supabase/supabase-js';

export async function onRequestPost(context) {
  const { request, env } = context;

  try {
    // 1. Verify Cron Authentication
    // To trigger this, the caller must send a POST request with the correct Bearer token matching ADMIN_CRON_KEY
    const authHeader = request.headers.get('Authorization');
    if (!authHeader || authHeader.replace('Bearer ', '') !== env.ADMIN_CRON_KEY) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { 
        status: 401,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // 2. Fetch last 7 days of feedback
    const supabaseAdmin = createClient(env.VITE_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);
    
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);
    
    const { data: feedbacks, error: dbError } = await supabaseAdmin
      .from('feedbacks')
      .select('rating, comment, created_at')
      .gte('created_at', sevenDaysAgo.toISOString())
      .order('created_at', { ascending: false });

    if (dbError) {
      throw new Error(`Database Error: ${dbError.message}`);
    }

    if (!feedbacks || feedbacks.length === 0) {
      return new Response(JSON.stringify({ message: "No feedback in the last 7 days. Skipped summary." }), { 
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // 3. Summarize with Gemini — return structured JSON for clean Discord formatting
    const { GoogleGenAI } = await import('@google/genai');
    const ai = new GoogleGenAI({ apiKey: env.GEMINI_API_KEY });
    
    const avgRating = (feedbacks.reduce((s, f) => s + f.rating, 0) / feedbacks.length).toFixed(1);
    const rawDataStr = feedbacks.map(f => `[${f.rating}⭐] ${f.comment || 'ไม่มีคอมเมนต์'}`).join('\n');
    
    const prompt = `คุณเป็น Product Manager ผู้เชี่ยวชาญ วิเคราะห์ Feedback ลูกค้าต่อไปนี้ (${feedbacks.length} รายการ, คะแนนเฉลี่ย ${avgRating}/5):

${rawDataStr}

ตอบกลับมาเป็น JSON เท่านั้น (ไม่มี markdown code block) โดยมีโครงสร้างดังนี้:
{
  "overall": "สรุปภาพรวม 1-2 ประโยค กระชับ ตรงประเด็น",
  "praise": "สิ่งที่ลูกค้าชอบ หรือ 'ยังไม่มีในสัปดาห์นี้' ถ้าไม่มี",
  "bugs": "ปัญหาด่วนที่ต้องแก้ หรือ '✅ ไม่พบปัญหาเร่งด่วน' ถ้าไม่มี",
  "requests": "ฟีเจอร์ที่ลูกค้าต้องการ หรือ 'ยังไม่มีในสัปดาห์นี้' ถ้าไม่มี",
  "action": "Next Action ที่แนะนำ 1 ข้อที่สำคัญที่สุด"
}
แต่ละ field ห้ามยาวเกิน 200 ตัวอักษร ใช้ภาษาไทย กระชับ เข้าใจง่าย`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.6-flash',
      contents: prompt,
      config: { 
        temperature: 0.2,
        responseMimeType: "application/json"
      }
    });

    let summary = { overall: '', praise: '', bugs: '', requests: '', action: '' };
    try {
      summary = JSON.parse(response.text);
    } catch(e) {
      summary.overall = response.text.trim().slice(0, 300);
    }

    // คำนวณสถิติดาว
    const starCounts = [1,2,3,4,5].map(s => ({ star: s, count: feedbacks.filter(f => f.rating === s).length }));
    const starBar = starCounts.reverse().map(s => s.count > 0 ? `${s.star}⭐ × ${s.count}` : null).filter(Boolean).join('  |  ');

    // 4. Send to Discord with structured embed fields
    const webhookUrl = env.DISCORD_WEBHOOK_WEEKLY_REPORT || env.DISCORD_WEBHOOK_URL;
    
    if (webhookUrl) {
      const payload = {
        username: "AutoScript Weekly Report 📈",
        avatar_url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f4c8.png",
        embeds: [{
          title: "🗓️ รายงาน Feedback รายสัปดาห์",
          color: 3447003, // Blue
          fields: [
            {
              name: "📊 ภาพรวมสัปดาห์",
              value: summary.overall || '-',
              inline: false
            },
            {
              name: "📈 สถิติคะแนนดาว",
              value: `**เฉลี่ย ${avgRating}/5** จาก ${feedbacks.length} รีวิว\n${starBar}`,
              inline: false
            },
            {
              name: "💖 ลูกค้าประทับใจ",
              value: summary.praise || '-',
              inline: true
            },
            {
              name: "🛠️ ปัญหาต้องแก้ด่วน",
              value: summary.bugs || '✅ ไม่พบปัญหา',
              inline: true
            },
            {
              name: "💡 ฟีเจอร์ที่เรียกร้อง",
              value: summary.requests || '-',
              inline: false
            },
            {
              name: "🎯 Next Action แนะนำ",
              value: summary.action || '-',
              inline: false
            }
          ],
          footer: {
            text: `Auto-generated by AutoScript AI • ข้อมูลจาก 7 วันที่ผ่านมา`
          },
          timestamp: new Date().toISOString()
        }]
      };

      await fetch(webhookUrl, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
    }

    return new Response(JSON.stringify({ success: true, count: feedbacks.length }), { 
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (err) {
    console.error("Weekly Summary API Error:", err);
    return new Response(JSON.stringify({ error: err.message || "Internal Server Error" }), { 
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}
